### PR TITLE
STMNIST addition to snntorch

### PR DESCRIPTION
**Pull request by shatoparbabanerjee**
Training on ST-MNIST with Tonic + snnTorch Tutorial

### CODE REVIEW

**Comment by jeshraghian** [comment]
Will check over the ipynb notebook shortly. Could you revert the title of Tutorial 6 back to what it was before? 
We don't want to change that.

**Comment by jeshraghian** [comment]
Note: you can just push another commit with the updated changes without making a new pull request. Everything will automatically be updated here.

**Comment by shatoparbabanerjee** [comment]
> Note: you can just push another commit with the updated changes without making a new pull request. Everything will automatically be updated here.

Sure I changed Tutorial 6 back, everything should be updated!

**Comment by jeshraghian** [comment]
Structure & results are really solid.
I've just started making some minor changes mainly to make things more succinct.

Could you update the following:
* A few of the title headers aren't loading properly and need a space between `##` and the text.
* remove the code blocks that are fully commented + unnecessary comments (e.g., s 1.7, and s 3)
* The test set accuracy plot isn't needed as there are only 3 sample points; I think you should just print the final value

Really cool stuff though; I'll have to share this with the OG authors of the ST-MNIST paper.

**Comment by shatoparbabanerjee** [comment]
> Structure & results are really solid. I've just started making some minor changes mainly to make things more succinct.
> 
> Could you update the following:
> 
> * A few of the title headers aren't loading properly and need a space between `##` and the text.
> * remove the code blocks that are fully commented + unnecessary comments (e.g., s 1.7, and s 3)
> * The test set accuracy plot isn't needed as there are only 3 sample points; I think you should just print the final value
> 
> Really cool stuff though; I'll have to share this with the OG authors of the ST-MNIST paper.

Do you want us to delete the code block in 1.5 which has the option to run the full transform vs short transform? Also there is a link in your tutorials where theres a button that says "open in drive" how do we get that GitHub colab link?

**Comment by jeshraghian** [comment]
> Do you want us to delete the code block in 1.5 which has the option to run the full transform vs short transform? 

Yep just go with one of the two transforms.

> Also there is a link in your tutorials where theres a button that says "open in drive" how do we get that GitHub colab link?

We need to merge this first and then the ipynb file will have a solid URL. 
In the meantime, just copy paste the URL from another tutorial and change the ipynb file name to this one.

**Pull request merged**
