### PR TITLE
State Quantization more robust for 2-bits

### PR DESCRIPTION
**Pull request by SreyesVenkatesh**
Made changes to make State Quantization more robust for 2-bits. Basically only changed the range of the for-loop and order of operations within the loops.

### CODE REVIEW

**Comment by jeshraghian** [comment]
This is a good addition - thanks for catching this.

However, I tested both this new version as well as the present version of state quantization in v0.7.0, but it seems like there is a bug somewhere... The membrane potential in the quantized case follows a totally different trajectory for low bits.

A link to the Colab notebook - have you had more luck with cross-checking quantized membranes vs full precision membranes?

https://colab.research.google.com/drive/1FTS5TSAgUgZD-ZidNrq6dojzs06gLeVM?usp=sharing

**Comment by ahenkes1** [comment]
Hey @SreyesVenkatesh , are there any updates on this? Best

**Comment by SreyesVenkatesh** [comment]
Hey Team,

I am looking at the code to see why the trajectory for the membrane potential of low-bit quantized neurons is not what is expected. So far I have found the following, 

1. For the lower the bit (ie. 4-bit or 2-bit) approximations, by increasing the rate of decay (ex. lowering Beta: 0.98 --> 0.5 etc. etc.) I was able to get the membrane potential to follow a trajectory that was closer to a full precision membrane potential trajectory. The general trend seems that the lower the bits used for approximation, the lower the Beta value would be required to achieve the ideal trajectory.    

2. There also does seem to be some sort of correlation between the value of the threshold, the decay rate (Beta), and the Quantization scheme (uniform, threshold centered, and even zero-centered), that would optimize the trajectory of the quantized membrane potential . 

3. I noticed that the error also occurs for the uniform quantization scheme, which I have not modified throughout my time working on this paper. This, combined with my previous findings is leading me to believe that there is some rounding/truncation noise that is happening when the quantized levels are being applied to the full precision levels which is leading to misrepresentations further down the line.   

I am still tracing through the code to try and find exactly where the discrepancy is happening so when I find something new I will let everybody know! Thank you very much!

**Comment by ahenkes1** [comment]
Hey @SreyesVenkatesh ! Thank you very much for your investigations! If you have news, feel free to reach out! Your contribution is very much appreciated!

**Pull request merged**
