### PR TITLE
add py3.12 to testing matrix

### PR DESCRIPTION
**Pull request by cclauss**
ERROR: Could not find a version that satisfies the requirement torch>=1.1.0 (from versions: none)

https://pypi.org/project/torch

### CODE REVIEW

**Comment by jeshraghian** [comment]
The 3.12 test is failing, I think it's because 3.12 is missing from tox.ini under [tox] and [gh-actions].

**Comment by cclauss** [comment]
`Travis CI - Pull Request Expected — Waiting for status to be reported Required` should probably be removed from the ___required___ tests below unless there is an active, paid subscription to Travis CI which is no longer free to open source projects.

**Comment by cclauss** [comment]
I think that adding `py312` to `tox.ini` will not solve the problem which looks like this:
```
py: install_deps> python -I -m pip install -r /home/runner/work/snntorch/snntorch/requirements_dev.txt
    [ ... ]
        File "/tmp/pip-build-env-vfl9zw5b/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 20, in <module>
      ModuleNotFoundError: No module named 'imp'
```
https://docs.python.org/3.12/whatsnew/3.12.html#imp so `setuptools` in `requirements_dev.txt` needs to be upgraded.

**Comment by cclauss** [comment]
```
      if: matrix.python-version == '3.12'
      run: pip install --upgrade setuptools
```

**Comment by jeshraghian** [comment]
It looks like we're still running into the same error above.

**Comment by cclauss** [comment]
Please re-approve te workflow so we can see if it passes.

**Comment by cclauss** [comment]
https://pypi.org/project/torch is not yet compatible with the current version of Python

**Comment by jeshraghian** [comment]
We can open this back up once PyTorch catches up to Python 3.12.

**Pull request closed without merging**
